name: Retrain Model

on:
  workflow_dispatch:
    inputs:
      csv_url:
        description: 'Google Drive Direct CSV URL'
        required: true
        type: string

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Run Training Script
        run: |
          python train1.py --data_path "${{ github.event.inputs.csv_url }}"

      - name: Upload Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/trained_model.pkl



# name: Retrain Model

# on:
#   workflow_dispatch:
#     inputs:
#       csv_url:
#         description: 'Google Drive Direct CSV URL'
#         required: true
#         type: string
        
# jobs:
#   retrain:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pandas scikit-learn

#       - name: Run Training Script
#         run: python train1.py --data_path "https://drive.google.com/uc?export=download&id=1PI1hMJR7dvDYwTZX3BON65fA9ZSMNMOb"

#       - name: Upload Trained Model
#         uses: actions/upload-artifact@v4
#         with:
#           name: trained-model
#           path: models/trained_model.pkl
