name: Retrain Model

on:
  push:
    branches:
      - main
      - main2
    paths:
      - "train.py"

  workflow_dispatch:
    inputs:
      retrain:
        description: "Trigger model retraining"
        required: false
        default: "false"
        

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run Training Script
        run: python train.py

      - name: Upload Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/trained_model.pkl
      
          
