name: Train or Retrain Model

on:
  workflow_dispatch:
    inputs:
      csv_url:
        description: 'Google Drive Direct CSV URL'
        required: true

  push:
    branches:
      - main
      - main2
    paths:
      - "train.py"

jobs:
  train-model:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dataset from URL
        run: curl -L "${{ github.event.inputs.csv_url }}" -o dataset.csv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas scikit-learn joblib

      - name: Train model with provided dataset
        run: python train.py --data_path dataset.csv

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/trained_model.pkl

  retrain-on-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Train model with default dataset
        run: python train.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/trained_model.pkl
